### ISSUE TITLE
No background image on mobile (iPhone X/Safari)

### ISSUE THREAD

**Issue by Wayneoween** [Wayneoween/dnd5e_story_bgdia#3]

**Comment by Ichaelus** [comment]
The issue is caused (big surprise) by the wrapper with the background image. The `background-attachment` property does not get a along very with with the `background-size` value (`auto, auto, auto 175%;`).

Consider these options:
- Change `background-size` to `cover`. This results however in a differently displayed cover image.
- Remove  the `background-attachment` property or change its value. It will cause the background image to appear on your iphone X - I'm just not sure about the implication of the now missing attribute.

Ichaelus
